---
- name: Provision AWS VPC and Network Resources
  # hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - ../variables/vars_network_environment.yaml

  tasks:
    - name: Web Application VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        state: "{{ vpc_state }}"
        cidr_block: "{{ vpc_cidr_block }}"
        region: "{{ vpc_region }}"
      register: vpc

    - name: Application/Webserver Subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        state: "{{ webapp_subnet_state }}"
        cidr: "{{ webapp_subnet_cidr }}"
        region: "{{ webapp_subnet_region }}"
      register: public_subnet

    - name: Application Database Subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        state: "{{ database_subnet_state }}"
        cidr: "{{ database_subnet_cidr }}"
        region: "{{ database_subnet_region }}"
      register: private_subnet

    - name: Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ webapp_subnet_igw_region }}"
        state:  "{{ webapp_subnet_igw_state }}"
      register: igw

    - name: NAT Gateway
      ec2_vpc_nat_gateway:
        subnet_id: "{{ public_subnet.subnet.id }}"
        state: "{{ database_subnet_nat_state }}"
        region: "{{ database_subnet_nat_region }}"
      register: nat_gateway

    - name: Public Route Table
      ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        state: "{{ webapp_subnet_route_table_state }}"
        region: "{{ webapp_subnet_route_table_region }}"
        subnets: [ "{{ public_subnet.subnet.id }}" ]
        routes:
          - dest: "{{ webapp_subnet_route_table_destination }}"
            gateway_id: "{{ igw.gateway_id }}"
      register: public_route_table

    - name: Private Route Table
      ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        state: "{{ database_subnet_route_table_state }}"
        region: "{{ database_subnet_route_table_region }}"
        subnets: [ "{{ private_subnet.subnet.id }}" ]
        routes:
          - dest: "{{ database_subnet_route_table_destination }}"
            gateway_id: "{{ nat_gateway.gateway.id }}"
      register: private_route_table
    
    - name: Create Resource IDs file
      command: touch ~/network_configuration_ids.yaml
    
    # Save The VPC, Private and Public Subnet IDs in YAML Config File
    - name: Export Subnet Info
      copy:
        content: |
          vpc_id                 : "{{ vpc.vpc.id }}"
          webappserver_subnet_id : "{{ public_subnet.subnet.id }}"
          database_subnet_id     : "{{ private_subnet.subnet.id }}"
        dest: ~/network_configuration_ids.yaml

    - name: Debug Info
      debug:
        var:
          vpc           : "{{ vpc.vpc }}"
          public_subnet : "{{ public_subnet.subnet }}"
          private_subnet: "{{ private_subnet.subnet }}"
          igw           : "{{ igw.gateway }}"
          nat_gateway   : "{{ nat_gateway.gateway }}"
          public_route_table :  "{{ public_route_table.route_table }}"
          private_route_table: "{{ private_route_table.route_table }}"
