---
- name        : "{{ play_name }}"
  hosts       : "{{ hosts }}"
  connection  : "{{ connection }}"
  gather_facts: "{{ gather_facts }}"
  vars_files:
    - ../variables/vars_appserver_instance.yaml
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Include Security Group IDs
    include_vars:
      file: ~/webapp_db_security_group_ids.yaml

    # This Task Launches an Application/Webserver EC2 Instance
  - name              : "{{ webapp_instance_task_name }}"
    ec2:
      image           : "{{ webapp_instance_image }}"
      instance_type   : "{{ webapp_instance_type }}"
      region          : "{{ webapp_instance_region }}"
      group_id        : "{{ webapp_instance_group_id }}"
      vpc_subnet_id   : "{{ webapp_instance_subnet_id }}"
      key_name        : "{{ webapp_instance_key_name }}"
      assign_public_ip: "{{ webapp_instance_assign_public_ip }}"
      count_tag:
        Name          : "{{ webapp_instance_count_tag }}"
      exact_count     : "{{ webapp_instance_exact_count }}"
      instance_tags:
        Name          : "{{ webapp_instance_instance_tags }}"
